
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myhome?useUnicode=true&characterEncoding=utf8
    username: root
    password: shdyd0509!

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
